version: '2'

networks: 
  dev:

services:

  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    image: dev-web-server
    networks: 
      - dev

  mongo:
    image: mongo:3.4
    networks: 
      - dev

  mysql-master:
    image: mysql:5.6
    volumes:
      - ./mysql/config/common.cnf:/etc/mysql/conf.d/common.cnf:ro
      - ./mysql/config/replication-master.cnf:/etc/mysql/conf.d/replication-master.cnf:ro
      - ./mysql/scripts/init/replication-master.sh:/docker-entrypoint-initdb.d/replication-master.sh:ro
      - ./data/mysql/master:/var/lib/mysql
    hostname: mysql-master
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks: 
      - dev

  mysql-slave:
    image: mysql:5.6
    volumes:
      - ./mysql/config/common.cnf:/etc/mysql/conf.d/common.cnf:ro
      - ./mysql/config/replication-slave.cnf:/etc/mysql/conf.d/replication-slave.cnf:ro
      - ./mysql/scripts/init/replication-slave.sh:/docker-entrypoint-initdb.d/replication-slave.sh:ro
      - ./data/mysql/slave:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - REPLICATION_MASTER_HOST=mysql-master
    depends_on: 
      - mysql-master
    networks:
      - dev

  pma:
    image: phpmyadmin/phpmyadmin:latest
    environment: 
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOSTS=mysql-master,mysql-slave
    ports: 
      - ${PMA_LOCAL_PORT}:80
    depends_on:
      - mysql-master
      - mysql-slave
    networks: 
      - dev

  sphinx:
    build:
      context: ./sphinx
      dockerfile: Dockerfile
    image: dev-sphinx
    tty: true
    networks: 
      - dev

  memcached:
    image: memcached:1.5
    networks: 
      - dev

  dev-full:
    image: tianon/true
    container_name: dev-full
    depends_on: 
      - web-server
      - memcached
      - mysql-master
      - mysql-slave
      - mongo
      - sphinx
      - pma